on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Cache WASM build
        uses: actions/cache@v3
        with:
          path: rust_backend/target
          key: rust_backend

      - name: Install dependencies for all packages
        run: pnpm install

      # NOTE: It's important to build @uatp/components _before_ uatp_template,
      # since the latter depends on it.
      - name: Test @uatp/components
        run: |
          pnpm --filter=@uatp/components build
          pnpm --filter=@uatp/components test

      - name: Test @uatp/template
        run: |
          pnpm --filter=@uatp/template rust
          pnpm --filter=@uatp/template python
          pnpm --filter=@uatp/template build
          pnpm --filter=@uatp/template test

      # pnpm can't do 'exec', have to use npm
      - name: Install npm
        uses: actions/setup-node@v4

      - name: Test @uatp/create-web Rust
        run: |
          npm exec packages/create-web -- --directory /tmp/rust --project-name rust --backend rust
          cd /tmp/rust/web
          pnpm install
          pnpm rust
          pnpm build

      - name: Test @uatp/create-web Python
        run: |
          npm exec packages/create-web -- --directory /tmp/python --project-name python --backend python
          cd /tmp/python/web
          pnpm install
          pnpm python
          pnpm build

      - name: Test @uatp/create-web no-backend
        run: |
          npm exec packages/create-web -- --directory /tmp/none --project-name none --backend none
          cd /tmp/none/web
          pnpm install
          pnpm build



  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install pnpm components
        run: |
          pnpm install

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

      - name: Update pre-commit
        uses: pre-commit-ci/lite-action@main
        if: always()
