name: CI Workflow
on:
    push:
      branches: [main, meta-test]

jobs:
  js-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Install and run tests
      run: |
        pnpm install
        pnpm run test
